dist: trusty
sudo: false
language: python
python: '3.6'
before_install:
- export TZ=Asia/Tokyo
install:
- pip install sphinx==1.6.4
- cd ..
- pwd
- ls -la
- git clone https://github.com/python-doc-ja/py36.git py36
- git clone --depth=5 -b intl-3.6 https://github.com/python-doc-ja/cpython-doc-intl.git cpython
- cd cpython/Doc
- ln -s ../../py36-locale locale
- ls -lF locale
- sphinx-build -D language=ja -D locale_dirs=locale -D gettext_compact=0 -A versionswitcher=1 -E -d build/doctrees . ../../py36
script:
- cd ../../py36
- git config user.email "travis-build-bot@example.com"
- git config user.name "Autobuild bot on Travis-CI"
- git pull origin master
- git add .
- if [ $(git status -s | wc -l) -eq 0 ]; then echo "nothing to commit"; exit 0; fi
- git commit -a -m "update html"
- git push --quiet "https://${GH_TOKEN}@github.com/python-doc-ja/py36.git" master:master

env:
  global:
    secure: "i8KiEKtytuAX7FOw5nOVNKXOI/UWEgSrV0lT9z5XTROeCG3hMcEOURoOxGesRY5tgNvX+lltWRA/nrMPEV0zXY/bdhsJ1ByylGB60xIu/+0Ek7t0h0OeOJWyi89v/xCXMYx5vHHWtjif1bi/42ebOgL7HK2iCJHBs6BIPUnvWbiuptHIFd5Oq86mmX7p8uhyUVRGckU2ClbB093n5I+jix8obC1YGikLqsoRO2E4MLMlDJNCGhsD+7OTqhIJqC32connqcJzLF0Vmf2j55EUPLnPyDy4ZylyypVJzj5mPN6Sqg4sF6rkdfr6E6n+0JAVtGwaG7YXRoLf7SBkuIsm+CoX85L5eji+qNH5iloeFCjpHRq2ZePAQANCL91dnysq3cvNzSnYLOE4Iwi4cg/dVuiIojgFDYuNW+v7KKDBITpsu6Q5tKhWe7l6cKUfpA8u5c30UI++MZMZJuRPzr83ina25CjwjCXhlEFpmMZTSEtpkpLevym5Ojn4eT0Mgj9mzXWqokXQMfjQuiMfeQ60iGW6wJuSo8pjHHByPHoAKJJC05Sl5QC/bY+FUorRj2a/3Zn8xv/fm/Vd4Edzrip3mWbAlnAlHg5c09sxZyiLOm+5+YVqlN+NtXwq/8XJO+C7xOT0+y0jEScQEIRlxCpJwABHt7uIyA1a5bsWYBjK0N4="
